blank_issues_enabled: false
contact_links:
  - name: Questions, Discussions, Ideas
    url: https://github.com/SimulationStorm/SimulationStorm/discussions/new
    about: Please ask and answer questions here.
